# Generated by Django 5.1.4 on 2024-12-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="idea",
            name="extra_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="idea",
            name="prototype_file",
            field=models.FileField(blank=True, null=True, upload_to="prototypes/"),
        ),
        migrations.AddField(
            model_name="idea",
            name="related_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="program",
            name="form_config",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
